### ISSUE TITLE
BSC - Transacciones de Entes

### ISSUE THREAD

**Issue by jmusanti** [InteligenciaAnalitica/BSC#105]
Se solicita la creación de un repositorio de datos en BI que tenga la información de transferencias recibidas y emitidas por clientes de nuestra entidad, con identificación de los siguientes datos: Cliente, CUIL/CUIT,  sucursal, cuenta digito

CUIL/CUIT, Cuenta digito, moneda, fecha, causal y transacción, cotización, monto, sector de origen y destino (atributo BCRA), numero de operación, usuario, CUIL/CUIT, Cuenta y CBU de destino.

La información deberá ser tanto de transferencias emitidas por nuestros clientes como transferencias recibidas por nuestros cliente, el origen pueden ser transferencias cursadas desde diferentes aplicativos:  SFB, desde Home banking, Interbanking datanet y MEP. Según información que dio sistemas hay dos tablas en SFB y dos de LINK que almacenan esta info, queda pendiente ver la información de los MEP procesados.

La prioridad hoy es identificar todas las transferencias emitidas del sector público con el sector del destino al que viajan (privado o público), no obstante el requerimiento es más amplio para resolver otras consultas a futuro.

Luego de esto se solicita la generación de un reporte mensual con la identificación de las 10 principales transferencias por monto que viajan de sector público al sector privado y/o financiero, por mes (los 10 mayores montos).

Saludos

**Comment by PabloGottig** [comment]
1.	Cruces con Txs Red Link: se explicó técnicamente como se van a consultar dichas tablas. Se propone replicar los datos de estas tablas a BI para mantener un histórico que luego pueda ser consumido por los usuarios.
Pasos a Seguir:
•	Pablo Alvarez deber definir si se va a mantener la tabla histórica en BI o si se generará un ID de cuenta en la tabla origen para vincularlo por universo directamente (como se hizo con Journals y Txs SFB) 
•	Independientemente de lo anterior, el proceso de BI mensual para transferencias del Sector Publico, traerá las txs del mes que este procesando en ese momento a BI para poder cruzarlas y recuperar CBU y CUIT del destinatario con la definición que envió Sistemas

2.	Cruces con Txs de Interbanking y SFB: se detecto que el cruce debe realizarse por Nro de Operación (TNUDOCTRA).
Pasos a Seguir:
•	IA deberá considerar este cruce en el proceso y recuperar el nro de operación de las tablas de txs de SFB (ACAHI y AHAHI). 

3.	Información del destinatario: se observa que en los casos en los que el destinatario no esté en la base de datos de clientes del banco no será posible recuperar ninguna información de la persona.
Pasos a Seguir:
•	IA en el proceso se intentará cruzar al destinatario por CUIT con la tabla de personas de BI, en caso de que exista, se vinculará con todos los datos disponibles del cliente. 

4.	Reportes en BI: se consultó si actualmente se están utilizando los reportes desarrollados y si la información está actualizada. Por otra parte se solicitó a Alfredo que revise y definan sobre cual de los reportes de transferencias del sector Público se desea incorporar la información.
Pasos a Seguir:
•	Alfredo Salomon: debe informar en que reporte debe agregarse la información solicitada o enviar el formato del reporte que se desea visualizar. 

Por favor incorporar o modificar cualquier comentario que consideren necesario.
