### ISSUE TITLE
PLA - Politica de actualizacion de legajos

### ISSUE THREAD

**Issue by jmusanti** [InteligenciaAnalitica/BSC#140]

**Comment by lsartoriIA** [comment]
Buen dia Joaquin,
Respecto al requerimiento de Reporte para la política de actualización de legajos, te voy adjuntando cual es instructivo que tenemos para realizar las exclusiones y quedar con el universo que debe actualizar, para que lo lean y vamos viendo en conferencia las dudas y explicaciones que se requieran.
 
Vayan teniendo en cuenta que vamos a necesitar que toda exlcusion podamos extraerla para verificar que es correcta. Por eejmplo la primer exclusión de clientes sin productos activos, tienen que proveernos cuales son los casos.
Tambien los datos de productos y transacciones que pudieran requerirse para las exclusiones, que sean consideradas como parametrizables.
 
Envianos una cita a través de zomm y lo vemos.
 
Te paso mi mail personal también, porque me resulta mas comodo unirme desde el celular. alfsalomon@gmail.com
